### ISSUE TITLE
Result is null

### ISSUE THREAD

**Issue by pblinux** [blackmann/locationpicker#29]
Hi.

I'm having troubles with picking a location, is always returning null. I checked #14 and  #24, I already have Geocoding enabled.

A RangeError message always shows when selecting a location.

```dart
RangeError (index): Invalid value: Valid value range is empty: 0
```

flutter doctor:
```bash
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by blackmann** [comment]
#14 requires you to enable billing for your account. Is that requirement met?

**Comment by pblinux** [comment]
Hi. @blackmann 
Yes, it's enabled. Actually, `google_mas_flutter` by itself works without issues. :thinking:

**Comment by ghost** [comment]
Found the cause.
<img width="826" alt="Screen Shot 2020-05-11 at 18 04 31" src="https://user-images.githubusercontent.com/23230582/81555197-5b184380-93b2-11ea-87f2-c6274b8ed149.png">
Because this api "https://maps.googleapis.com/maps/api/geocode/json" return "address_components", that has less fields than expected.
In this case, address_components has only 4 fields, so it through an exception.
Solution,
Updated this statement as the result's format.

**Comment by ghost** [comment]
I think the result's format depend on the country.

**Comment by blackmann** [comment]
Hi @blackblack915, I think 7 is out of bounds and must have been a typo. Fixing it now.

**Comment by ghost** [comment]
> setState(() {
        if (result['address_components'] is List && result['address_components'].length >= 7) {
          this.locationResult = LocationResult()
            ..name = result['address_components'][0]['short_name']
            ..locality = result['address_components'][1]['short_name']
            ..latLng = latLng
            ..formattedAddress = result['formatted_address']
            ..placeId = result['place_id']
            ..postalCode = result['address_components'][7]['short_name']
            ..country = AddressComponent.fromJson(result['address_components'][6])
            ..administrativeAreaLevel1 = AddressComponent.fromJson(result['address_components'][5])
            ..administrativeAreaLevel2 = AddressComponent.fromJson(result['address_components'][4])
            ..city = AddressComponent.fromJson(result['address_components'][3])
            ..subLocalityLevel1 = AddressComponent.fromJson(result['address_components'][2])
            ..subLocalityLevel2 = AddressComponent.fromJson(result['address_components'][1]);
        }
        else {
          this.locationResult = LocationResult()
            ..latLng = latLng
            ..formattedAddress = result['formatted_address']
            ..placeId = result['place_id']
            ..name = result['address_components'][0]['short_name']
            ..locality = result['address_components'][1]['short_name']
            ..administrativeAreaLevel1 = AddressComponent.fromJson(result['address_components'][2])
            ..city = AddressComponent.fromJson(result['address_components'][3])
            ..country = AddressComponent.fromJson(result['address_components'][4]);
        }
      });

@blackmann  My solution.

**Comment by blackmann** [comment]
oh yes, you're right. Just found out the result length is variable.

**Comment by blackmann** [comment]
Can you provide a merge request with this solution? @blackblack915

**Comment by ghost** [comment]
sure @blackmann

**Comment by ghost** [comment]
remote: Permission to blackmann/locationpicker.git denied to blackblack915.
fatal: unable to access 'https://github.com/blackmann/locationpicker.git/': The requested URL returned error: 403
@blackmann plz grant permission

**Comment by blackmann** [comment]
First fork this project, the clone it and create a new branch, say `address-comp-fix`. Then make your changes.

Commit the changes and then push to origin (that is, your fork). Then visit this repo and go to the Pull Request tab, you'll see your changes and you can submit it for review there.

(I suppose you're new to open source contributions)

**Comment by ghost** [comment]
I found a new solution. Use the component's types.
I made a pull request. Plz review it.

> String name, locality, postalCode, country, administrativeAreaLevel1, administrativeAreaLevel2, city, subLocalityLevel1, subLocalityLevel2;
        bool isOnStreet = false;
        if (result['address_components'] is List<dynamic> && result['address_components'].length != null && result['address_components'].length > 0){
          for (var i = 0; i < result['address_components'].length; i++){
            var tmp = result['address_components'][i];
            var types = tmp["types"] as List<dynamic>;
            var shortName = tmp['short_name'];
            if (types == null) {
              continue;
            }
            if (i == 0) {
              // [street_number]
              name = shortName;
              isOnStreet = types.contains('street_number');
              // other index 0 types
              // [establishment, point_of_interest, subway_station, transit_station]
              // [premise]
              // [route]
            }
            else if (i == 1 && isOnStreet) {
              if (types.contains('route')) {
                name += ", $shortName";
              }
            }
            else {
              if (types.contains("sublocality_level_1")){
                subLocalityLevel1 = shortName;
              }
              else if (types.contains("sublocality_level_2")){
                subLocalityLevel2 = shortName;
              }
              else if (types.contains("locality")){
                locality = shortName;
              }
              else if (types.contains("administrative_area_level_2")){
                administrativeAreaLevel2 = shortName;
              }
              else if (types.contains("administrative_area_level_1")){
                administrativeAreaLevel1 = shortName;
              }
              else if (types.contains("country")){
                country = shortName;
              }
              else if (types.contains('postal_code')){
                postalCode = shortName;
              }
            }
          }
        }
        locality = locality ?? administrativeAreaLevel1;
        city = locality;
        this.locationResult = LocationResult()
          ..name = name
          ..locality = locality
          ..latLng = latLng
          ..formattedAddress = result['formatted_address']
          ..placeId = result['place_id']
          ..postalCode = postalCode
          ..country = AddressComponent(name: country, shortName: country)
          ..administrativeAreaLevel1 = AddressComponent(name: administrativeAreaLevel1, shortName: administrativeAreaLevel1)
          ..administrativeAreaLevel2 = AddressComponent(name: administrativeAreaLevel2, shortName: administrativeAreaLevel2)
          ..city = AddressComponent(name: city, shortName: city)
          ..subLocalityLevel1 = AddressComponent(name: subLocalityLevel1, shortName: subLocalityLevel1)
          ..subLocalityLevel2 = AddressComponent(name: subLocalityLevel2, shortName: subLocalityLevel2);
      });

**Comment by andbitty** [comment]
Hey @blackmann is this issue merged ?

I still receive null (with the emulator)

**Comment by AxeemHaider** [comment]
Hi @blackmann 

I'm also having the same issue can you please merge the pull request. Thanks.

**Comment by sehejjain** [comment]
@AxeemHaider Did you enable the GeoCoding API? 
GeoCoding API is needed for this to work.

**Comment by AxeemHaider** [comment]
@sehejjain Yes I did enable Geocoding API. And billing is also enable in my account. 
I have a same error which has @blackblack915 
`RangeError (index) Invalid value not in range 0..5, inclusive 7`

I see @blackblack915 create a pull request to solve this problem but this pull request is not merged don't why.

**Comment by faisalmushtaq007** [comment]
i'm having the same NULL problem and i've tried everything without the billing thing. Is it necessary to enable billing?

**Comment by pblinux** [comment]
@faisalmushtaq007 Yes, you must have billing enabled. This issue happens because some fields length in result are variable. We're waiting for #30 to be merged.

**Comment by ghost** [comment]
@AxeemHaider @faisalmushtaq007 while waiting for the pull request merged, you can edit the cached file on your computer (place_picker.dart) as my solution above. It'll work.

**Comment by AxeemHaider** [comment]
@blackblack915 why owner is not merging this pull request. It seems this repo is no longer maintain

**Comment by ghost** [comment]
@AxeemHaider i don't know. he's disappeared. 🥶

**Comment by Parassharmaa** [comment]
For the time being use the following dependency:

```
  place_picker:
    git:
      url: https://github.com/blackblack915/locationpicker.git
      ref: address-components-fix
```

**Comment by blackmann** [comment]
😬😬😬 Sorry the fix has been merged for a long while now. I'm sorry for being absent.

**Comment by Dararii** [comment]
Still have the problem on version 0.9.17. Help.

**Comment by ghost** [comment]
@Dararii plz provide more detail

**Comment by UnluckyY1** [comment]
@blackblack915 still having the same problem 
google places + maps are enabled

```
I/flutter (30443): {error_message: This API project is not authorized to use this API., results: [], status: REQUEST_DENIED}
I/flutter (30443): error
I/flutter (30443): RangeError (index): Invalid value: Valid value range is empty: 0
```

**### Solved, i had to create a new project in google console everything works well now <3**
